# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92f1a28ab8ed88e3aa54123130d9565ee90c2cbf02287cb5fa90c9441c05ac7c1a311a7c6ebb88b7390d128fa513a64e8d7aa55f08c009894e958364fb2834c9

test:
  secret_key_base: 3acd1cdb9b5de93442f812e172789c4cc6184b129a4b96be5acde3b5bfb04a9eeb2b8e5ceff0aaeda84c196a2868fb5dbd9475fe110f244abcd7b3437304f5c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
